version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "mineflayer"
        dependency-type: "all"
    commit-message:
      prefix: "bump(deps): bump `mineflayer` to "
    open-pull-requests-limit: 0